// apps/svelte/src/components/Tracker.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte"
  import { stringify } from "@cursed/utils"
  import { socket } from "../socket"

  export let isActive = false

  function handleMove(event: MouseEvent | TouchEvent) {
    if (!isActive) return

    const source = "touches" in event ? event.touches[0] : event
    if (!source) return

    socket?.send(
      stringify({
        type: "move",
        coords: {
          x: (source.clientX / window.innerWidth) * 100,
          y: (source.clientY / window.innerHeight) * 100,
        },
      }),
    )
  }

  onMount(() => {
    window.addEventListener("mousemove", handleMove)
    window.addEventListener("touchmove", handleMove)
  })

  onDestroy(() => {
    window.removeEventListener("mousemove", handleMove)
    window.removeEventListener("touchmove", handleMove)
  })
</script>

// app/components/Tracker.tsx
"use client"

import { useEffect, useState } from "react"
import { useSocket } from "../hooks"
import { stringify } from "../lib"

export function Tracker() {
  const [isActive, setIsActive] = useState(true)
  const { socket } = useSocket()

  useEffect(() => {
    function publish(e: MouseEvent | Touch) {
      socket?.send(
        stringify({
          coords: {
            x: (e.clientX / window.innerWidth) * 100,
            y: (e.clientY / window.innerHeight) * 100,
          },
          type: "move",
        }),
      )
    }

    const handleMove = (e: MouseEvent) => publish(e)
    const handleTouch = (e: TouchEvent) =>
      e.touches[0] ? publish(e.touches[0]) : null

    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") {
        setIsActive(false)
      } else if (e.key === " ") {
        setIsActive((prev) => !prev)
      }
    }

    window.addEventListener("keydown", handleKeyDown)
    if (isActive) {
      window.addEventListener("mousemove", handleMove)
      window.addEventListener("touchmove", handleTouch)
    }

    return () => {
      window.removeEventListener("keydown", handleKeyDown)
      window.removeEventListener("mousemove", handleMove)
      window.removeEventListener("touchmove", handleTouch)
    }
  }, [isActive, socket])

  return null
}
