// apps/react/src/components/Cursors.tsx
import { createRef, useEffect, useState } from "react"
import { parse, ServerConnection } from "@cursed/utils"
import { useSocket } from "../hooks"
import { ClientConnection } from "../types"
import { Cursor } from "./Cursor"

type ConnectionMap = Record<string, ClientConnection>

function makeClientConnection(connection: ServerConnection): ClientConnection {
  return {
    ...connection,
    ref: createRef<HTMLDivElement>(),
  }
}

export function Cursors() {
  const { socket } = useSocket()
  const [cursors, setCursors] = useState<ConnectionMap>({})

  useEffect(() => {
    function handleMessage(e: MessageEvent) {
      const data = parse(e.data)

      switch (data.type) {
        case "init":
          setCursors(
            data.connections.reduce<ConnectionMap>((acc, connection) => {
              acc[connection.id] = makeClientConnection(connection)
              return acc
            }, {}),
          )
          break

        case "connect":
          if (!cursors[data.connection.id]) {
            setCursors((prev) => ({
              ...prev,
              [data.connection.id]: makeClientConnection(data.connection),
            }))
          }
          break

        case "disconnect":
          setCursors((prev) => {
            const { [data.connectionId]: _, ...next } = prev
            return next
          })
          break

        case "move": {
          const cursor = cursors[data.connectionId]
          const { x, y } = data.coords

          if (cursor && cursor.ref.current) {
            cursor.ref.current.style.visibility = "visible"
            cursor.ref.current.style.setProperty("--x", `${x}vw`)
            cursor.ref.current.style.setProperty("--y", `${y}vh`)
          }
        }
      }
    }

    socket?.addEventListener("message", handleMessage)

    return () => {
      socket?.removeEventListener("message", handleMessage)
    }
  }, [cursors, socket])

  return (
    <>
      {Object.values(cursors).map((connection) => (
        <Cursor
          key={connection.id}
          ref={connection.ref}
          connection={connection}
        />
      ))}
    </>
  )
}

// apps/svelte/src/components/Cursors.svelte
<script lang="ts">
  import { parse, type ServerConnection } from "@cursed/utils"
  import Cursor from "./Cursor.svelte"
  import { onDestroy, onMount } from "svelte"
  import { socket } from "../socket"

  let cursors: ConnectionMap = {}

  type ConnectionMap = Record<string, ClientConnection>

  function makeClientConnection(
    connection: ServerConnection,
  ): ClientConnection {
    return {
      ...connection,
      // ref: createRef<HTMLDivElement>(),
    }
  }

  function handleMessage(e: MessageEvent) {
    const data = parse(e.data)

    switch (data.type) {
      case "init":
        cursors = data.connections.reduce<ConnectionMap>((acc, connection) => {
          acc[connection.id] = {
            ...connection,
            // ref: createRef<HTMLDivElement>(),
          }

          return acc
        }, {})
        break

      case "connect":
        if (!cursors[data.connection.id]) {
          cursors[data.connection.id] = makeClientConnection(data.connection)
        }
        break

      case "disconnect":
        delete cursors[data.connectionId]
        break

      case "move": {
        const cursor = cursors[data.connectionId]

        if (cursor && cursor.ref.current) {
          cursor.ref.current.style.visibility = "visible"
          cursor.ref.current.style.setProperty("--x", `${data.coords.x}vw`)
          cursor.ref.current.style.setProperty("--y", `${data.coords.y}vh`)
        }
      }
    }
  }

  onMount(() => {
    socket?.addEventListener("message", handleMessage)
  })

  onDestroy(() => {
    socket?.removeEventListener("message", handleMessage)
  })
</script>

{#each Object.values(cursors) as connection}
  <Cursor ref={connection.ref} {connection} />
{/each}
